When using CMake, always also build single-precision variant.
devernay/cminpack pull request #45
Opened 2020-12-14 16:19 UTC by anntzer

Closes #41 (per https://github.com/devernay/cminpack/issues/41#issuecomment-622253014).
(Only the second commit matters for the feature, but cleaning the style helped me understand the logic :))

2020-12-15 01:19 UTC, devernay requested changes
Thank you!

I'm OK with this change, but can you move the doc about building with cmake, and the fact that it builds both libraries, is a separate section of the doc as indicated below?

I would also like feedback from other contributors (@xantares @bherisse  @tadeu @chaplin89): Is everyone OK with systematically building the 2 versions?

Also, why not the "long double" (128-bit float) version? The "half" version is really just a proof-of-concept, but "long double" may be useful if precision is an issue. long double is not supported by every compiler/platform so there would have to be a test for that. I'm not a CMake afficionado, so I don't know the proper way of testing this, but the FFTW configure script does this test.

2020-12-15 01:20 UTC, devernay commented
Also, it's OK to reformat the CMakelist, but it's easier to review if it's a separate PR.

2020-12-15 07:28 UTC, xantares commented
Are you sure you need both variants at the same time ? What's the use-case ?
Maybe a cmake option to select the variant is what we need.
I dont want to build the lib twice.

2020-12-15 13:48 UTC, anntzer commented
> Are you sure you need both variants at the same time ? What's the use-case ?

The use case is when cminpack is packaged by redistributors, which include at least linux distros and conda.  In that case they will typically just provide a "plain" build of the library, which here means only the double-precision version.  I would rather have them provide all precisions together, so that I can easily have whatever precision I need (single, in my case) on machines with no compiler available.

> Maybe a cmake option to select the variant is what we need.  I dont want to build the lib twice.

Per the above I believe the default should be to provide all of them (because otherwise I'd need to go to each and every redistributor and convince them that they should do a non-default build of the library), but we could reasonably add a CMake flag to just build one of them.

2020-12-15 14:17 UTC, anntzer commented on docs/index.html
> +<p>If you want to use the single precision CMinpack, you should define __cminpack_float__ before including <code>cminpack.h</code>. __cminpack_half__ has to be defined for the half-precision version
done

2020-12-16 17:20 UTC, devernay commented
@xantares are you satisfied by @anntzer 's replies?

To me it looks OK:
- only one build
- two libraries are installed (could be three, including the long double version which IMHO would be a valuable addition, but we can leave that for later)

2020-12-16 19:25 UTC, devernay commented
can you rebase and push the changes?

2020-12-16 19:27 UTC, devernay approved these changes

2020-12-16 19:31 UTC, anntzer commented
done

2020-12-16 19:51 UTC, devernay commented
Side note: @xantares and @anntzer would you agree to be collaborators on this project? This would allow you to merge PRs, but they would still need to be reviewed and approved by someone else.

2020-12-16 19:52 UTC, merged

2020-12-16 19:52 UTC, devernay commented
@anntzer I'm curious, do you have an automatic formatter for CMakeLists or did you do it by hand?

2020-12-16 20:07 UTC, anntzer commented
I did it by hand plus some regexes...

2020-12-16 20:35 UTC, anntzer commented
Thanks for the offer of being a collaborator.  I don't claim any expertise in the relevant field (I really just needed a reasonable implementation of `lmdif`) and already have much on my plate, but can try to occasionally have a look if you need help with something.  No time guarantees, though :-)

2021-02-02 16:03 UTC, anntzer commented
@devernay Any chance for a new release with these changes?  Thanks!

2021-02-10 05:07 UTC, devernay commented
Done!

2021-02-10 09:22 UTC, anntzer commented
Thanks!